<a href="https://colab.research.google.com/github/madhumaram/microservicesfirstproject/blob/master/single_ml_perceptrons_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np # linear algebra np.random.seed(10)
import pandas as pd # data processing, CSV file I/O (e.g., pd.read_csv )
import matplotlib.pyplot as plt
import seaborn as sns
           # Required magic to display matplotlib plots in notebooks
%matplotlib inline 
#reading the files
data_train = pd.read_csv('train.csv')

In the code cell below, we used the function head() with argument 4 to display the first four rows of the dataset. You should adjust the code below to display eight rows in the dataset.

In [7]:
data_train.head(8)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S

In the code below, we have defined a dictonary dict_live , which maps the entries in the column Survived from 0 and 1 to Perished and Survived , respectively.

In [8]:
# We define a dictionary to transform the 0,1 values in the # labels to a String that defines the fate of the passenger 
dict_live = {
               0 : 'Perished',
               1 : 'Survived'
           }

In the code below, fill the ellipsis in the definition of the dictonary dict_sex to map the entries in the column Sex from male and female to 0 and 1 , respectively.

In [9]:
# We define a dictionary to assign labels 0 or 1 
# corresponding to the sex
dict_sex = {
    'male' : 0,
    'female' : 1 
    }

Run the code cell below, to create the column BSex with the values in dict_sex and append it to the dataframe. After running, you should see this new data as the right-most column in the dataframe.

In [10]:
#We apply the dictionary using a lambda function and the pandas .apply () module
data_train['BSex'] = data_train['Sex'].apply(lambda x: dict_sex[x])
#This line displasy the dataframe with the new column
data_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  BSex  
0      0         A/5 21171   7.2500   NaN        S     0  
1      0          PC 17599  71.2833   C85        C     1  
2      0  STON/O2. 3101282   7.9250   NaN        S     1  
3      0            113803  53.1000  C123        S     1  
4      0            373450   8.0500   NaN        S     0

In the code cell below, fill the ellipsis with Pclass and BSex to indicate a list with these two values as our two-dimensional feature vector. Note that we used the function to_numpy() to convert our features to
NumPy arrays.

In [12]:
# Now the features are a 2 column matrix whose entries are 
# the Class (1,2,3) and the Sex (0,1) of the passengers 
features = data_train[['Pclass', 'BSex']].to_numpy() 
print(features)

[[3 0]
 [1 1]
 [3 1]
 ...
 [3 1]
 [1 0]
 [3 0]]


***Implementing the Perceptron***

The function sigmoid_act takes as argument a vector z and returns the output a .

In [15]:
# Define the sigmoid activator 
def sigmoid_act(z):
  # sigmoid
  a = 1/(1+ np.exp(-z)) 
  return a

The function ReLU_act takes as argument a vector z and returns the output a .

In [16]:
# We may employ the Rectifier Linear Unit (ReLU) 
def ReLU_act(z):
  return max(0, z)

Now, we are ready to define the perceptron.
In the code cell below, we have defined a function, perceptron , that takes as input an array X representing the features in the dataframe that we wish to use and the argument act selecting the activation function.

In [18]:
def perceptron(X, act):
  np.random.seed(1) #seed for reproducibilty
  shapes = X.shape #get the number of (rows, columns)
  n = shapes[0] + shapes[1] #adding the number of rows and colums
  # Generating random weights and bias
  w = 2*np.random.random(shapes) - 0.5 #we want initial w between -1 and 1
  w_0 = np.random.random(1)
  # Initialize the function
  f = w_0[0]
  for i in range(0, X.shape[0]-1): #run over column elements
    for j in range(0, X.shape[1]-1): #run over rows elements
      f += w[i, j]*X[i,j]/n #adding each component of input multiplied by corresponding weight
  # Pass it to the activation function and return it as an output 
  if act == 'Sigmoid':
      output = sigmoid_act(f) 
  elif act == "ReLU":
      output = ReLU_act(f) 
  return output          

An example of an output of the perceptron with the sigmoid activation is given below:

In [20]:
print('Output with sigmoid activator: ', perceptron(features, act = 'Sigmoid'))

Output with sigmoid activator:  0.8331095577932985


In the code cell below, try to generate the output by using the ReLU function. Simply observe the code above and fill - in the ellippsis with the name of the function that defined the desired activation.

In [22]:
print('Output with ReLU activator: ', perceptron(features, act = "ReLU"))

Output with ReLU activator:  1.607827593037905


**Single-Layer Perceptron in sklearn**

The library sklearn offers a built-in implementation of a single-layer perceptron. Even better, the implementation also knows how to calculate gradients of all parts of the perceptron, and use that information to implement back-propagation.

In this next example, we use a perceptron learner to classify the famous iris dataset (https://scikit- learn.org/stable/auto_examples/datasets/plot_iris_dataset.html) offered by the sklearn library.


In [24]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler 
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score

In the next cell, we import the iris dataset from sklearn .

In [25]:
# Load the iris dataset
iris = datasets.load_iris()
# Create our X and y data
X = iris.data
y = iris.target

Run the code bell below to visualize the first five rows of the array X .

In [27]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [28]:
# View the first 100 observations of our y data 
y
 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Split The Iris Data into Training and Test

In [31]:
# Split the data into 75% training data and 25% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
X_train.shape, X_test.shape

((112, 4), (38, 4))

Preprocess the X Data by Scaling

In [32]:
sc = StandardScaler() 
sc.fit(X_train)

StandardScaler()

Finally, to complete this, we need to apply the scaler to both the X_train set and the X_test set.
Run the code cell by filling the ellipsis with the X_test set.

In [33]:
# Apply the scaler to the X training data
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

***Train a Single-Layer Perceptron Model***
Next, we need to train the Perceptron classifier on the scaled X_train data with the corresponding labels in Y_train .

Run the code cell below. Inside the classifier Perceptron , set the learning rate eta0 equal to 0.1 and the random_state equal to 1. Note that by default, the sklearn Perceptron uses a ReLU activation function.

In [34]:
# Create a perceptron object with the parameters:max_ieter (epochs) eq ual to 40 learning rate of 0.1
ppn = Perceptron(max_iter = 1000, eta0 = 0.1, random_state = 0) 
# Train the perceptron
ppn.fit(X_train_std, y_train)

Perceptron(eta0=0.1)

Now we can use this trained perceptron, ppn , to predict the results for the scaled test data.
In the code cell below, fill in the ellipsis with the name of the variable corresponding to the set above.

In [35]:
# Apply the trained perceptron on the X data to make predicts for the y test dat
y_pred = ppn.predict(X_test_std)
y_pred

array([2, 1, 2, 0, 0, 2, 1, 2, 2, 2, 0, 2, 1, 1, 2, 0, 2, 2, 2, 0, 2, 0,
       1, 1, 0, 0, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 0, 1])

We can compare the predicted y with the true y . Run the code cells below to examine these.

In [36]:
y_pred

array([2, 1, 2, 0, 0, 2, 1, 2, 2, 2, 0, 2, 1, 1, 2, 0, 2, 2, 2, 0, 2, 0,
       1, 1, 0, 0, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 0, 1])

In [37]:
y_test

array([2, 1, 1, 0, 0, 2, 1, 2, 2, 2, 0, 2, 1, 1, 1, 0, 2, 2, 2, 0, 2, 0,
       1, 1, 0, 0, 2, 0, 1, 0, 2, 2, 2, 1, 1, 0, 0, 1])

Finally, we can evaluate the accuracy of our model by using the function accuracy_score from sklearn , which uses the formula: 
accuracy = 1 -  observations predicted wrong/total observations

Run the code below to evaluate the accuracy of our model.

In [38]:
# View the accuracy of the model, which is: 1 - (observations predicte d wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.92


***Train a Multilayer Perceptron (MLP) Model***

In [40]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000) 
mlp.fit(X_train_std, y_train)

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

In [41]:
mlp_y_pred = mlp.predict(X_test_std)
mlp_y_pred

array([2, 1, 2, 0, 0, 2, 1, 2, 2, 2, 0, 2, 1, 1, 1, 0, 2, 1, 2, 0, 2, 0,
       1, 1, 0, 0, 2, 0, 1, 0, 2, 2, 2, 1, 1, 0, 0, 1])

In [42]:
# View the accuracy of the model, which is: 1 - (observations predicte d wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, mlp_y_pred))

Accuracy: 0.95
